### ISSUE TITLE
插件使用到SharePreference，报空指针，怎么破？

### ISSUE THREAD

**Issue by leafseelight** [bunnyblue/ACDD#10]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

**Comment by bunnyblue** [comment]
sample项目？

**Comment by leafseelight** [comment]
关掉哈！是我插件程序的问题导致的，刚才想把它关掉来着，一时没找到地方。还是谢谢你！
