### ISSUE TITLE
关于资源加载问题

### ISSUE THREAD

**Issue by shazzen** [bunnyblue/ACDD#11]
你好，我想请问下为什么要通过修改buildtools的方式去加载资源呢？我试过可以仅仅通过反射调用addAssertPath的方式加载资源。
也可能是我的demo太过简单，还没遇到坑。

**Comment by bunnyblue** [comment]
插件同时运行就歇菜了

**Comment by shazzen** [comment]
你指的同时运行是什么意思呢？插件中运行插件？还是加载两个插件？

**Comment by bunnyblue** [comment]
多个同时运行，有资源依赖的你也搞不定吧
