### ISSUE TITLE
Bundle 加载到 /data/data/com.b5mandroid/files/storage/ 目录问题

### ISSUE THREAD

**Issue by Cenler** [bunnyblue/ACDD#12]
正在研究使用，发现一个问题:就是应用启动初始化时读取auto配置插件进行安装过程中会出现文件无法转移，代码执行完了也看不到目标目录产生，错误如下：
com.b5mandroid FileLock /data/data/com.b5mandroid/files/storage/com.b5m.plugin.account/version.1/lock Lock FAIL! open failed: ENOENT (No such file or directory)

Failed to get file lock for /data/data/com.b5mandroid/files/storage/com.b5m.plugin.account/version.1/bundle.zip

Failed optDexFile '/data/data/com.b5mandroid/files/storage/com.b5m.plugin.account/version.1/bundle.zip' >>>

查看目录后发现文件及目录（/com.b5m.plugin.account/version.1）不存在，望解答

**Comment by Tiny1213** [comment]
我昨天试过多次后发现，是我把apk包放在armeabi下，但是实际运行的时候加载了armeabi-v7a的库，你试试。我两个目录下都放了插件就ok

**Comment by bunnyblue** [comment]
@Cenler  你的bundle的文件放哪个目录下了？
@Tiny1213  不用放两份啊，不占用资源吗？放一份就可以了，你们最好描述下你们libs下面的动态库目录结构

**Comment by Tiny1213** [comment]
需要两份啊，运行的时候只加载一个jni库目录的吧，反正armeabi和armeabi-v7a都放一份就ok了

**Comment by bunnyblue** [comment]
如果你原来的目录只有armeabi-v7a就不用copy一份armeabi，直接把dexopt 复制到armeabi-v7a就好了 @Tiny1213

**Comment by Tiny1213** [comment]
因为别的第三方同时提供了armeabi-v7a和armeabi的库，所以没办法，必须有两个目录的

**Comment by Cenler** [comment]
补充下几点： 插件包是可以读取到的

**Comment by Cenler** [comment]
问题和Bundle放哪没有关系，插件是可以读取到
补充几点：插件包是可以读取到的 问题出在  Framework.installNewBundle() 中的 ACDDFileLock.LockExclusive() 方法中 ，我打断点一步一步走不会出现问题,直接运行就会导致 ACDDFileLock.LockExclusive() 执行异常，我猜测是那块读写锁的问题

**Comment by Cenler** [comment]
另外补充一个问题 为什么你的工程里面插件加载后不会创建 bundle.zip 文件
@bunnyblue

**Comment by bunnyblue** [comment]
无法复现

**Comment by hejie** [comment]
dependency 的作用是什么？

**Comment by hejie** [comment]
"dependency": [] 的作用是什么？

**Comment by bunnyblue** [comment]
@hejie  配置模块依赖，A依赖B，启动A的时候回自动安装B或者启动B

**Comment by hejie** [comment]
thanks

2016-03-15 8:59 GMT+08:00 Bunny Blue <notifications@github.com>:

> @hejie <https://github.com/hejie> 配置模块依赖，A依赖B，启动A的时候回自动安装B或者启动B
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/bunnyblue/ACDD/issues/12#issuecomment-196590195
>



-- 
内容：

*顺  祝  工  作  顺  利!*


*研发部     何杰*

*电话：**18667168171          **邮编：**200081*
