### ISSUE TITLE
运行是提示 java.lang.RuntimeException: Parcelable encounteredClassNotFoundException reading a Serializable object (name = com.xxx.bean.xxx)错误

### ISSUE THREAD

**Issue by DavidYes** [bunnyblue/ACDD#13]
是ACDD不支持插件app使用Serializable object吗？整个log如下：
11-20 11:53:23.916 26510-26510/org.acdd.launcher E/linker: load_library(linker.cpp:759): library "libmaliinstr.so" not found
11-20 11:53:35.330 26510-26510/org.acdd.launcher W/System.err: java.lang.RuntimeException: Parcelable encounteredClassNotFoundException reading a Serializable object (name = com.xxx.xxx)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.os.Parcel.readSerializable(Parcel.java:2148)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.os.Parcel.readValue(Parcel.java:2016)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.os.Parcel.readMapInternal(Parcel.java:2226)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.os.Bundle.unparcel(Bundle.java:223)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.os.Bundle.getBoolean(Bundle.java:803)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.content.Intent.getBooleanExtra(Intent.java:4354)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at org.acdd.runtime.stub.BundlePackageManager.processActivityIntentIfNeed(BundlePackageManager.java:656)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:185)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
11-20 11:53:35.332 26510-26510/org.acdd.launcher W/System.err:     at android.os.Looper.loop(Looper.java:194)
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5391)
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err:     at dalvik.system.NativeStart.main(Native Method)
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err: Caused by: java.lang.ClassNotFoundException: com.xxx.xxx
11-20 11:53:35.333 26510-26510/org.acdd.launcher W/System.err:     at java.lang.Class.classForName(Native Method)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.lang.Class.forName(Class.java:217)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:2304)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1663)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:683)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1806)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.io.ObjectInputStream.readObject(ObjectInputStream.java:2006)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1963)
11-20 11:53:35.334 26510-26510/org.acdd.launcher W/System.err:     at android.os.Parcel.readSerializable(Parcel.java:2142)
11-20 11:53:35.335 26510-26510/org.acdd.launcher W/System.err: 	... 15 more
11-20 11:53:35.335 26510-26510/org.acdd.launcher W/System.err: Caused by: java.lang.NoClassDefFoundError: com.xxx.xxx
11-20 11:53:35.336 26510-26510/org.acdd.launcher W/System.err: 	... 25 more

**Comment by bunnyblue** [comment]
已经修复了记得，你用的最新版本吗

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by DavidYes** [comment]
是用的最新的版本！

**Comment by bunnyblue** [comment]
找不到的类在插件里面？是从一个插件往另一个插件传递还是怎么传递

**Comment by bunnyblue** [comment]
ACDDConfig.stubModeEnable 先把这个设为false
