### ISSUE TITLE
DELAY，AUTO，STORE 的意义？

### ISSUE THREAD

**Issue by DavidYes** [bunnyblue/ACDD#14]
/***延时启动配*****/
    public static String[] DELAY = new String[]{};
    public static String[] AUTO = new String[]{};
    public static String[] STORE = new String[]{}; 这三个配置可否详细说明一下？各为什么目的？我发现有时引入的so文件中手机的app文件夹的lib目录没有.so，但是files/storage里面是有解压后的apk的。

昨天测试arcode的动态更新，发现Demo里面更新其实是可以的，只是需要将主宿app杀掉进程重启后，才能重新加载qrcode，请问，可以加载后直接重新reload qrcode这个插件，不用重启主宿吗？

**Comment by bunnyblue** [comment]
auto里面的是随机启动，自动跟随宿主启动，delay是延时启动，store用的时候在安装到宿主
