### ISSUE TITLE
请问 child模块 可以共享 主程序的 资源吗？  是不是只有child模块编译的时候才需要替换 aapt

### ISSUE THREAD

**Issue by mkrcpp** [bunnyblue/ACDD#17]
请问 child模块 可以共享 主程序的 资源吗？  是不是只有child模块编译的时候才需要替换 aapt

**Comment by bunnyblue** [comment]
资源可以共享，默认xml共享，直接引用资源就行，child模块必须替换aapt完成资源分区和资源共享支持

**Comment by mkrcpp** [comment]
比如 主程序有  某些 图片/dimens/values 
这些也能通过 R.drawable,* 引用吗？
因为我发现只能provided jar

如果不能引用id, 会不会出现 资源重复问题

**Comment by mkrcpp** [comment]
亦或者，我直接拷贝一份公共的 资源 ，图片，values 全部拷贝到 每一个 child模块中？
另外 能简要说明  对  360 的  DroidPlugin 吗？或者 AndFix.
亦或者携程的 DynamicAPK ？
360的不能互相引用资源，这可能导致 包过大
携程的号称可以互相引用图片等资源

**Comment by bunnyblue** [comment]
参照 https://github.com/bunnyblue/ACDDExtension/blob/master/Samples/public.xml 你把需要共享的资源定义进来就好了，参照android sdk里。 然后在你的xml中直接@资源就行了  脚本里面有个共享资源的引用，把xml文件指向就行了。
不能直接 R.drawable,* 引用，后面修改下，应该支持的
360的那个机制很巧妙，360的初衷就是个各个组件完全隔离，代码和资源级别的隔离。降低耦合。
Andfix单纯的代码热修复，没直接关系

**Comment by mkrcpp** [comment]
Got it! Thanks for the answer!

**Comment by bunnyblue** [comment]
@mkrcpp  https://github.com/bunnyblue/ACDDExtension/commit/8ae2a8c1f457d4686761d9ce94e6092da5efad88 产生resource.jar 支持代码和布局引用
