### ISSUE TITLE
Error:Execution failed for task ':HomeLauncher:processAcddDebugResources'. > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Programfile\android\sdk_studio\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value -16842752

### ISSUE THREAD

**Issue by Honsec** [bunnyblue/ACDD#19]
1.新建项目
2. 导入eclipse 项目 sample（homelauncher 等等）
3. 替换我build.gradle指定的 23.0.2SDK 目录下的appt.exe 
4.编译

结果如下。
Error:Execution failed for task ':HomeLauncher:processAcddDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Programfile\android\sdk_studio\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value -16842752

Build Failed

请问我错在哪里。。

**Comment by bunnyblue** [comment]
不再支持eclipse开发，需要使用Studio开发 gradle 插件版本1.3或者更新版本

**Comment by Honsec** [comment]
我在 android studio 下

做了一个modle  
          修改build 文件 添加以下代码
productFlavors {
        acdd {
            aaptOptions.additionalParameters '--ACDD-resoure-id', '0x7b', '--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()
        }
        normal {
        }
    }

编译完成后。把 debug_signed apk 重命名为  .so文件 添加到  sample项目中的Launcher 包下。


编译时 提示

Error:(118, 1) Execution failed for task ':ACDDLauncher:acddWrapBundle'.
> Process 'command 'C:\Program Files\Java\jdk1.7.0_67\bin\java.exe'' finished with non-zero exit value 1

是母包设置错误还是   子模块错误?

**Comment by bunnyblue** [comment]
你看下脚本里面acddWrapBundle 这个的话把apk处理产生json信息还有修正文件名，你看下studio message窗口里面的信息，看看是不是空指针还是什么错误，去掉隐私信息贴上来看下

**Comment by Honsec** [comment]
Information:Gradle tasks [:HomeLauncher:assembleAcddDebug]
:HomeLauncher:preBuild UP-TO-DATE
:HomeLauncher:preAcddDebugBuild UP-TO-DATE
:HomeLauncher:checkAcddDebugManifest
:HomeLauncher:prepareAcddDebugDependencies
:HomeLauncher:compileAcddDebugAidl UP-TO-DATE
:HomeLauncher:compileAcddDebugRenderscript UP-TO-DATE
:HomeLauncher:generateAcddDebugBuildConfig UP-TO-DATE
:HomeLauncher:generateAcddDebugAssets UP-TO-DATE
:HomeLauncher:mergeAcddDebugAssets UP-TO-DATE
:HomeLauncher:generateAcddDebugResValues UP-TO-DATE
:HomeLauncher:generateAcddDebugResources UP-TO-DATE
:HomeLauncher:mergeAcddDebugResources FAILED
Error:Execution failed for task ':HomeLauncher:mergeAcddDebugResources'.
> C:\Users\chief\Desktop\Dynamic_test\HomeLauncher\src\main\res\values\styles.xml: Error: In DataSet 'main', no data file for changedFile. This is an internal error in the incremental builds code; to work around it, try doing a full clean build.
Information:BUILD FAILED
Information:Total time: 0.87 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by bunnyblue** [comment]
C:\Users\chief\Desktop\ACDD-master\ACDDLauncher\assets 这个路径存在吗？
```
org.apache.commons.io.FileUtils.writeStringToFile(new File(targetFile), jsonArray.toString());
```
出错的代码这样子，你看下路径存在不。手头木有windows电脑，暂时没发测试你的问题

**Comment by Honsec** [comment]
存在asset  ，我没有配置asset 下的 json 。
是这个原因么

**Comment by bunnyblue** [comment]
不是，那个json生成

**Comment by Honsec** [comment]
删除json 里面的 内容后 编译成功了！！

**Comment by bunnyblue** [comment]
源码位于https://github.com/bunnyblue/ACDDExtension/tree/master/buildTools/BundleTool ，有时间的话自己挑下，不太清楚什么情况

**Comment by Honsec** [comment]
好的。非常感谢。

**Comment by Honsec** [comment]
怪了。。。

我添加的 文件名为 libcom_acdd_module_test.so   （原名：module_test-acdd-debug.apk）

然后添加了 manifests

在BootApp中 修改了如下代码 （添加了 module_test）
	ACDDConfig.AUTO = new String[]{"com.acdd.homelauncher","cn.acdd.qrcode","com.acdd.universalimageloader.sample","com.example.chief.module_test"};


运行后界面中 找不到我的 包名。  json 文件里头也没有

**Comment by bunnyblue** [comment]
你把你的插件给我发一份吧，明天我看下

**Comment by Honsec** [comment]
怎么发。

**Comment by bunnyblue** [comment]
bunnyblueair@gmail.com

**Comment by Honsec** [comment]
好的。

**Comment by bunnyblue** [comment]
你的包名不要有下划线，去掉看下

**Comment by Honsec** [comment]
e我试试

**Comment by Honsec** [comment]
刚刚用QQ 邮箱发送了邮件。 gmail 不让我发代码。 安全隐患说为了防范病毒，

**Comment by Honsec** [comment]
我的模块步骤是这样的。
1.新建android studio 项目  
2.在项目目录下 导入 public.xml ，gradlew.bat  ，keystore
3.替换指定build toolversion 下的 asset .exe文件
4. 新建module  修改build.gradle下的 配置文件  

   signingConfigs {
        config {
            keyAlias 'AndroidDebugKey'
            keyPassword 'android'

            storeFile rootProject.file('accd_debug.keystore')
            storePassword 'android'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
        debug {
            signingConfig signingConfigs.config
        }
    }
    productFlavors {
        acdd {
            aaptOptions.additionalParameters '--ACDD-resoure-id', '0x7b', '--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()
        }
        normal {
        }
    }


5.编译模块。

生成APK文件。

1.打开项目 ACDDLauncher
2.在 libs/armeabi 下 放入apk文件 并且重命名为 .so  (libcom_acdd_myapptest.so)
3.Manifest 声明。（我的模块包名是 com.example.chief.myapplication）
4.在BootApp.java 文件夹下 修改如下代码（添加了 com.example.chief.myapplication）
        
      ACDDConfig.AUTO = new String[]{"com.acdd.homelauncher","cn.acdd.qrcode","com.acdd.universalimageloader.sample","com.example.chief.myapplication"};

5.删除 asset 下的json 文件内容。 置为空文件。
6.编译。

编译成功。

但是主页面中不显示我的包名
只显示 {"com.acdd.homelauncher","cn.acdd.qrcode","com.acdd.universalimageloader.sample"}

**Comment by bunnyblue** [comment]
你把你的json发过来

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by Honsec** [comment]
[{"pkgName":"cn.acdd.qrcode","version":"1.0","activities":["com.acdd.qrcode.CaptureActivity","com.acdd.qrcode.MainActivity"],"services":[],"receivers":["com.acdd.qrcode.QRReceiver"],"contentProviders":[],"dependency":[],"md5":"4bb68c3c2df296734f623e46f138499f","size":624746,"hasSO":true},{"pkgName":"com.acdd.android.appcenter","version":"1.0","activities":["com.acdd.android.appcenter.main.GcContainerActivity","com.acdd.android.appcenter.main.ActivityInternalActivity"],"services":["com.acdd.android.appcenter.download.GcAppDownLoadService"],"receivers":["com.acdd.android.appcenter.GameStaticReceiver"],"contentProviders":["com.acdd.android.appcenter.AppProvider"],"dependency":["com.acdd.homelauncher"],"md5":"a88b69014f8752cf90c7d875367250ab","size":34279,"hasSO":false},{"pkgName":"com.acdd.android.game2","version":"1.0","activities":["com.acdd.android.game2.main.ActivityInternalActivity","com.acdd.android.game2.main.GcContainerActivity"],"services":["com.acdd.android.game2.download.GcAppDownLoadService"],"receivers":["com.acdd.android.game2.GameStaticReceiver"],"contentProviders":["com.acdd.android.game2.GameProvider"],"dependency":[],"md5":"5f56e604b189a59d2dcaec6808090b50","size":30080,"hasSO":false},{"pkgName":"com.acdd.homelauncher","version":"1.0","activities":["com.acdd.homelauncher.NativeFragmentActivity","com.acdd.homelauncher.MainActivity"],"services":["com.acdd.homelauncher.DaemonService"],"receivers":[],"contentProviders":[],"dependency":[],"md5":"3405a1ccaf3d1677c20a1d4c70032864","size":36771,"hasSO":false},{"pkgName":"com.example.chief.myapplication","version":"1.0","activities":["com.nextapps.naswall.NASWallBrowser","com.nextapps.naswall.NASWall","com.example.chief.myapplication.MainActivity"],"services":[],"receivers":[],"contentProviders":[],"dependency":[],"md5":"950a29451007e17f49865cecac99b92b","size":1211207,"hasSO":false},{"pkgName":"com.acdd.testapp1","version":"1.0","activities":["com.acdd.testapp1.MainActivity"],"services":[],"receivers":[],"contentProviders":[],"dependency":[],"md5":"efc9000d3b843c148f29d3b09ea4f2f8","size":35969,"hasSO":false},{"pkgName":"com.acdd.testapp2","version":"1.0","activities":["com.acdd.testapp2.MainActivity"],"services":[],"receivers":["com.acdd.testapp2.TestApp2Receiver"],"contentProviders":[],"dependency":[],"md5":"6e76be943a2948a1ab5da7ef0b11cd7d","size":35944,"hasSO":false},{"pkgName":"com.acdd.universalimageloader.sample","version":"1.0","activities":["com.nostra13.universalimageloader.sample.activity.HomeActivity","com.nostra13.universalimageloader.sample.activity.ComplexImageActivity","com.nostra13.universalimageloader.sample.activity.SimpleImageActivity"],"services":[],"receivers":["com.nostra13.universalimageloader.sample.widget.UILWidgetProvider"],"contentProviders":[],"dependency":[],"md5":"eddc894e066919cf173e77841b087049","size":400340,"hasSO":false}]

**Comment by Honsec** [comment]
ACDDConfig.AUTO = new String[]{"com.acdd.homelauncher","cn.acdd.qrcode","com.acdd.universalimageloader.sample","com.acdd.android.game2","com.example.chief.myapplication"};

我尝试 别的包名是否会一样不能加载。
测试结果 game2 能正确加载。 
我的包名 chief.myapplication 没能加载

**Comment by Honsec** [comment]
http://note.youdao.com/share/?id=e95f217e96a3b18b3d7fed585114c64b&type=note

这是项目文件。 母包及 子模块

**Comment by bunnyblue** [comment]
ACDD-master/ACDDLauncher/libs/armeabi/libcom_example_chief_myapplication.so
哥哥，你的包名时chief，看下wiki好不，你编译出的插件放到arm那个目录。后缀apk，程序会自动改名，不用手动改名

**Comment by Honsec** [comment]
非常感谢。 
我打开了多次 一直没有发现 1 Get Start  是能点击的链接。
