### ISSUE TITLE
在MultiDex的情况下适用ACDD

### ISSUE THREAD

**Issue by xk009** [bunnyblue/ACDD#2]
在我的application 继承 ACDDAPP 的情况下，使用MultiDex.install(this); 加载Secondary DEX 的时候carsh了。日志如下：
![image](https://cloud.githubusercontent.com/assets/13362331/9921623/0b07411a-5d12-11e5-9a1a-864b57073d23.png)
原因是
![image](https://cloud.githubusercontent.com/assets/13362331/9921645/4f051fcc-5d12-11e5-9d19-7e06e778c0ab.png)
当前应用的classloader已经替换为ACDD自己的classloader. 导致在这个classloader中找不到pathList这个字段。
是不是在使用 MultiDex的情况下，不能使用ACDD?

**Comment by bunnyblue** [comment]
你用最新版的代码试下，initACDD，attach 调用multi-dex之后手动调用initACDD，支持multi-dex，可能初始化的时机不对，你在你的Application应该先install dex，然后再掉super

**Comment by xk009** [comment]
可以了，感谢。
