### ISSUE TITLE
关于框架的介绍

### ISSUE THREAD

**Issue by jianhaobinan** [bunnyblue/ACDD#20]
您好，因为搜索到了贵项目，发现贵项目的相关介绍和资料比较少，能否提供一些稍微详细些的介绍呢？比如项目采用的实现方式，跟正常的app相比有哪些限制或不足，在插件开发时是否需要遵循某些规则？如果能有一个简单的介绍文档也可以对使用您项目的的人提供更好的帮助不是吗？谢谢

**Comment by bunnyblue** [comment]
看wiki谢谢
