### ISSUE TITLE
如何实现 联网下载插件并安装到主包

### ISSUE THREAD

**Issue by Honsec** [bunnyblue/ACDD#21]
根据上次提问。我仔细阅读了wiki。 这次又要拜托作者帮忙了。

目前我想实现的是，不把apk 文件放到 armeabi 文件夹下。 
我想要让我的 打包好的apk 能够从我的服务器中下载 APK 或者已经处理好的SO 文件  ，动态加载。

这个可以实现么。我猜测是 ACDD.getInstance().installBundle() 这个函数 。
然后我的代码结果如下。

**Comment by Honsec** [comment]
在WelcomeFragment.java 文件的 init() 函数下。
加入以下代码
try {
            String loacation= Environment.getExternalStorageDirectory().getAbsolutePath();
            Log.d("data", loacation);
            File exists=new File(loacation+"/libcom_example_chief_myapplication.so");
            if(exists.exists()){
                Log.d("data","exist");
            }else{
                Log.d("data","not exist");
            }
            ACDD.getInstance().installBundle(loacation,new File(loacation+"/libcom_example_chief_myapplication.so"));
        } catch (BundleException e) {
            e.printStackTrace();
        }

**Comment by Honsec** [comment]
报错信息如下。


12-16 23:42:31.629 22571-22571/org.acdd.launcher D/data: /storage/emulated/0
12-16 23:42:31.639 22571-22571/org.acdd.launcher D/data: exist
12-16 23:42:31.639 22571-22571/org.acdd.launcher E/ACDDFileLock: org.acdd.launcher FileLock /data/data/org.acdd.launcher/files/storage/storage/emulated/lock Lock FAIL! open failed: ENOENT (No such file or directory)
12-16 23:42:33.799 22571-22571/org.acdd.launcher W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.framework.BundleClassLoader.resolveBundle(BundleClassLoader.java:160)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.framework.BundleImpl.resolveBundle(BundleImpl.java:154)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.framework.BundleImpl.<init>(BundleImpl.java:112)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.framework.Framework.installNewBundle(Framework.java:404)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.framework.ACDD.installBundle(ACDD.java:168)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.launcher.welcome.WelcomeFragment.init(WelcomeFragment.java:209)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.launcher.welcome.WelcomeFragment.onCreateView(WelcomeFragment.java:150)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.Fragment.performCreateView(Fragment.java:2114)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:833)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.Activity.performStart(Activity.java:6411)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2771)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:181)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:193)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.os.Looper.loop(Looper.java:145)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6145)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
12-16 23:42:33.919 22571-22571/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err: org.osgi.framework.BundleException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.framework.Framework.installNewBundle(Framework.java:415)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.framework.ACDD.installBundle(ACDD.java:168)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.launcher.welcome.WelcomeFragment.init(WelcomeFragment.java:209)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.launcher.welcome.WelcomeFragment.onCreateView(WelcomeFragment.java:150)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.Fragment.performCreateView(Fragment.java:2114)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:833)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.Activity.performStart(Activity.java:6411)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2771)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:181)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:193)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.os.Looper.loop(Looper.java:145)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6145)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
12-16 23:42:33.979 22571-22571/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by Honsec** [comment]
我不知道      如何动态的用代码 安装模块,升级模块, 删除模块.

**Comment by bunnyblue** [comment]
这个项目只有核心代码，插件模块均位于https://github.com/bunnyblue/ACDDExtension
installBundle 填写插件的包名 。ACDD里面安装 卸载更新，周日更新温度

**Comment by Honsec** [comment]
作者。 文档更新了么，  我找不到啊。

**Comment by bunnyblue** [comment]
最近忙，还没整理完，ACDD入口的你可以看下源码里面的，要晚一些，最近工作忙

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by Honsec** [comment]
哦 。 好的。

我再次确认下 做好的APP能 网络下载安装 子APP 是吧？

**Comment by dashen19930328** [comment]
你好，你这个已经实现了吗？

**Comment by RichesJson** [comment]
我认为，其实只要把so文件放到宿主apk的so文件存放目录下就可以了啊。按理说不需要去更改底层的内核吧。Android不是本身就有包管理器这东西，启动apk时就会自动去读取宿主底下的so文件吧。360就是基于这个原理做了包管理器。ACDD其实就是Bundle化，对吧
