### ISSUE TITLE
关于支持Fragment问题

### ISSUE THREAD

**Issue by whwzm88** [bunnyblue/ACDD#22]
您好,目前该框架，支持这种模式吗，例如：

在主工程的一个Activity页面，可以将插件的Fragment包进来吗？  类似于动态View加载的原理?

**Comment by bunnyblue** [comment]
可以，不过比较麻烦，你要先找到fg所在的包，启动这个包之后然后找fg的class

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2015-12-17 17:17 GMT+08:00 吴志敏 <notifications@github.com>:

**Comment by whwzm88** [comment]
目前的框架，核心的功能，是不是比较适用于主工程和插件之间，完全解耦，交互较少，数据交互也少的情况呢》？ 而且数据传递只能通过传统的Activity或者广播的形式，进行交互呢？

**Comment by bunnyblue** [comment]
程序启动之后插件之间可以进行通信，你可以忽略插件的存在，耦合多的话，如果你能拆分的话也行，就是比较麻烦，公用的类keep出来要，正常情况下都在一个进程里面，所以应该还好，eventbus之类的都行

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2015-12-17 17:26 GMT+08:00 吴志敏 <notifications@github.com>:

**Comment by bunnyblue** [comment]
可以设置依赖，manifest设置好了就行，使用meta-info
