### ISSUE TITLE
如何编译

### ISSUE THREAD

**Issue by RichesJson** [bunnyblue/ACDD#24]
作者你好，看到你的这套框架以后，发现文档很少，我想问下，关于你的这个项目怎么在android studio里面编译呢。需要用到哪些模块进行编译

**Comment by bunnyblue** [comment]
wiki里面不是写了吗？没看懂

**Comment by bunnyblue** [comment]
[wiki](https://github.com/bunnyblue/ACDD/wiki/Get-Start-Zh!)

**Comment by RichesJson** [comment]
恩，如何支持动态升级呢。我想从网络上下载插件的话

**Comment by bunnyblue** [comment]
ACDD.update

**Comment by RichesJson** [comment]
哦，好的。因为我看你wiki里面说的是从lib/arm下面加载插件的。所以不是很了解呵呵

**Comment by bunnyblue** [comment]
文档的话看javadoc吧，这个跟着源码一起发的都是，没单独写到wiki

**Comment by RichesJson** [comment]
好的 谢谢了

**Comment by RichesJson** [comment]
奇怪了，这个源码下载下来没有看到javadoc文档呢

**Comment by bunnyblue** [comment]
https://jcenter.bintray.com/org/acdd/ACDDCore/

**Comment by RichesJson** [comment]
我这边热更新是不是要将网络上下载下来的插件然后copy到libs/arm下才行？如果我一开始宿主里面没放置插件，这个Bundle-info.json文件还要生成吗

**Comment by bunnyblue** [comment]
不用，ACDD.update 填写包名和其余插件路径就行了,你试试吧，不行的话把信息插进去就行了，应该需要，组建管理跟这个有关

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2015-12-18 15:09 GMT+08:00 RichesJson <notifications@github.com>:

**Comment by RichesJson** [comment]
是这样用的吗？ACDD.getInstance().installOrUpdate

**Comment by bunnyblue** [comment]
```

    /**
     * update bundle,when app  restart,update will change
     *
     * @param pkgName     bundle's package name
     * @param mBundleFile bundle archive file
     * @throws BundleException
     * @see {@link #updateBundle(String location, InputStream inputStream) updateBundle}
     */
    public void updateBundle(String pkgName, File mBundleFile) throws BundleException
```

**Comment by RichesJson** [comment]
那这个意思是我更新插件完了以后，必须要重新启动APP了

**Comment by bunnyblue** [comment]
对，设计的这样，如果你确保没依赖的话可以用Force结尾的生效，不然的话最好等启动自动生效

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by RichesJson** [comment]
就是说，我如果用Force结尾，就可以马上生效了吧

**Comment by RichesJson** [comment]
你好，这块有没有用ant生成的方式，目前我们合作伙伴用的是eclipse呢。
 productFlavors {
        acdd {
            aaptOptions.additionalParameters '--ACDD-resoure-id', '0x70', '--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()
        }
        normal {
        }
    }

**Comment by bunnyblue** [comment]
不提供ant，不太熟悉

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by RichesJson** [comment]
那我如果直接用appt打包，这个命令要怎么写

**Comment by bunnyblue** [comment]
原来的基础上加 --ACDD-resoure-id  --ACDD-shared-resources
完整参数 gradle assembleDebug  --info 获取

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by RichesJson** [comment]
恩，不是用gradle打包的，是说直接用aapt命令搞的。
aapt 命令要怎么写呢。谢谢楼主了

**Comment by bunnyblue** [comment]
aapt不能的环境不一样，没发跟 完整的

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by RichesJson** [comment]
额，这样啊。不是用你git里面的那个aapt环境就可以打包的吗

**Comment by bunnyblue** [comment]
不行

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by RichesJson** [comment]
对了，之前看altas这个视频。各个插件是运行在一个类似沙盒的环境下。视频里面有说一个点，就是插件崩溃了。不会引起宿主的崩溃

**Comment by RichesJson** [comment]
不知道现在这个插件化有没有支持这个功能

**Comment by Honsec** [comment]
希望作者 把 doc 链接 https://jcenter.bintray.com/org/acdd/ACDDCore/  复制到wiki 在上只写了 doc 字样。

谢谢作者一直以来的支持

**Comment by dashen19930328** [comment]
最后你的插件怎么编译的呢，我现在自己写的一个demo插件，按照wiki步骤来，最后aapt报错，不知道什么原因
