### ISSUE TITLE
OptDexProcess这个类是做什么的?

### ISSUE THREAD

**Issue by RichesJson** [bunnyblue/ACDD#27]
作者你好，我们这边有个需求，就是点击某一插件的时候，再去启动插件。看了你的源码里面，
OptDexProcess 这个是做什么用的？

**Comment by bunnyblue** [comment]
优化dex  oat或者odex

**Comment by RichesJson** [comment]
看了你的源码，你这里主要是使用OSGI的模式，通过framework来管理bundle的资源和类。是不是启动bundle以后，通过bundleListener监控bundler的运行情况。并且每个bundle运行在一个独立的线程里面，形成一个沙盒环境吗

**Comment by bunnyblue** [comment]
没，单进程模式
