### ISSUE TITLE
组件包之前怎么通讯

### ISSUE THREAD

**Issue by RichesJson** [bunnyblue/ACDD#28]
看了你的源码是用osgi的做法，我现在想问下，bundle和bundle在atlas中是怎么互相通讯的。是通过android自己的广播呢还是通过event事件，还是说通过Export-Package？

**Comment by bunnyblue** [comment]
都行，不用纠结osgi，单进程模式，广播事件都支持

**Comment by RichesJson** [comment]
哦，就是intent传值就可以了是吧

**Comment by bunnyblue** [comment]
嗯

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by RichesJson** [comment]
这个有没有沙盒机制呢，就是一个插件崩了以后，会不会影响主程序。插件的大小有没有限制

**Comment by bunnyblue** [comment]
没有，会，没有。
单进程模式，想不影响宿主的话给插件配置个process

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2015-12-28 9:51 GMT+08:00 RichesJson <notifications@github.com>:

**Comment by RichesJson** [comment]
没有沙盒机制吗？怎么给插件配置个process呢。是说一定要安装在手机上，还是？

**Comment by bunnyblue** [comment]
manifest

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by RichesJson** [comment]
有点不明白呢，你是说给插件的LauncherActivity这东西配置process?

**Comment by RichesJson** [comment]
是这样设置吗？<application>元素的 android:process，那跨进程的话，组件之间必须要通过AIDL来通讯吧，那这样就不知道咋办了（AIDL模式还得写AIDL）

**Comment by RichesJson** [comment]
是这样设置吗<application>元素的 android:process，那跨进程的话，组件之间必须要通过AIDL来通讯吧，那这样就不知道咋办了（AIDL模式还得写AIDL）

**Comment by RichesJson** [comment]
是这样设置吗application节点中配置 android:process，那跨进程的话，组件之间必须要通过AIDL来通讯吧，那这样就不知道咋办了（AIDL模式还得写AIDL）

**Comment by bunnyblue** [comment]
跟普通的app一样啊要是跨进程的话都得用aidl了
