### ISSUE TITLE
关于类加载器的问题

### ISSUE THREAD

**Issue by xk009** [bunnyblue/ACDD#3]
我在Host和bundle应用都引入了recyclerview（由于是aar，剥离不掉）。 宿主 和 插件apk中 都包含  
```java 
        View recyclerView = view.findViewById(android.R.id.list);

        Log.d("recyclerView", recyclerView.getClass().getClassLoader().getClass().getName());
        Log.d("RecyclerView", RecyclerView.class.getClassLoader().getClass().getName());
```

这段代码，打印对应的ClassLoader.
现象：我先点击宿主的，会打印 PathClassLoader , PathClassLoader。 在点击插件apk中打印BundleClassLoader, PathClassLoader。
如果点击顺序反过来的话，会先打印插件的 BundleClassLoader，BundleClassLoader。
在打印宿主的PathClassLoader， BundleClassLoader。
求问，怎么保证类加载 加载的类 字节码保持同一份？？

**Comment by bunnyblue** [comment]
插件中不应该存在宿主中已经存在的类，recyclerview 这个你把jar取出来，编译组件的时候provided就行了

 Across the Great Firewall, you can reach every corner in the world.
                                                          *Best Regards*

2015-09-18 10:39 GMT+08:00 xk009 <notifications@github.com>:

**Comment by xk009** [comment]
但是 不可避免 有些是aar, provdied 不了。比如 appcompat
