### ISSUE TITLE
关于osgi与崩溃隔离

### ISSUE THREAD

**Issue by yuzhijun** [bunnyblue/ACDD#30]
想问下，在你的代码里面看到有osgi的包，可是好像没有看到有使用到，这样插件崩溃了是不是会影响到宿主程序

**Comment by bunnyblue** [comment]
影响，插件是单进程模式

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2015-12-29 16:05 GMT+08:00 yuzhijun <notifications@github.com>:
