### ISSUE TITLE
osgi的作用与延迟加载

### ISSUE THREAD

**Issue by yuzhijun** [bunnyblue/ACDD#31]
你这框架里面是不是没有osgi也没多大的影响？还有框架里面插件有延迟加载吗

**Comment by bunnyblue** [comment]
影响不大，有延迟加载

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2015-12-29 17:33 GMT+08:00 yuzhijun <notifications@github.com>:
