### ISSUE TITLE
master项目， 会报java.io.FileNotFoundException: bundle-info.json 这个错误

### ISSUE THREAD

**Issue by j062cheng** [bunnyblue/ACDD#36]
master项目导进我的studio， 重新编译运行。 java.io.FileNotFoundException: bundle-info.json
01-11 10:33:12.909 6420-6420/org.acdd.launcher W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
01-11 10:33:12.909 6420-6420/org.acdd.launcher W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:323)
01-11 10:33:12.909 6420-6420/org.acdd.launcher W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:297)
我看asserts 下，  bundle-info.json文件是存在的。 删掉bundle-info.json，再执行，  能生成新的bundle-info.json， 但还是会报相同的错。

**Comment by bunnyblue** [comment]
看下apk里面有这文件吗

**Comment by j062cheng** [comment]
apk里真没有bundle-info.json, 

打包时可能失败了。
报的错是：
Execution failed for task ':ACDDLauncher:acddWrapBundle'.
> Process 'command 'D:\programfiles\Java\jdk1.7.0_80\bin\java.exe'' finished with non-zero exit value 1 。

我这个这个设置已经从你原来项目中的 1.6改成1.7了， 我用的是1.7。  其实下面是_1_6的配置得出的效果也是一样的。
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7  
        targetCompatibility JavaVersion.VERSION_1_7
    }

task acddWrapBundle << {
    javaexec {
        classpath "$projectDir/ACDDExt.jar"
        main = 'org.acdd.ext.bundleInfo.maker.BundleMakeBooter'
        args "$projectDir/libs/armeabi".toString(), "$projectDir/assets/bundle-info.json".toString(),"$projectDir/.bundleCache"
    }
}
args 这行有黄色的小警告。
'args' cannot be applied to '(java.lang.String, java.lang.String, groovy.lang.GString)' 
This inspection reports assignments with incompatible types     
被gradle 弄得头有点晕， 谢谢了。

**Comment by bunnyblue** [comment]
你看下堆栈吧，没有log不知道原因

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by j062cheng** [comment]
你好，  这个问题没能解决。  但是绕过去了。  
生成josn 后 再把
assembleDebug.dependsOn(acddWrapBundle)
assembleRelease.dependsOn(acddWrapBundle) 注释掉。  打包就能带有assets下的josn文件了。 
或者生成acddcore.jar.   launcher工程在eclipse下打包。    

再有问下，  不再支持eclipse的原因是  打包package id 不便吗。  谢谢了。

**Comment by bunnyblue** [comment]
Google都不在维护ADT了，我也没必要维护了
