### ISSUE TITLE
关于免注册

### ISSUE THREAD

**Issue by dashen19930328** [bunnyblue/ACDD#4]
您好，我想问就是说这个框架好像支持免注册activity与receiver，service也可以通过动态创建注册而免注册，但是provider等其它组件免注册做了吗？其实也有实际用途，毕竟应用添加免注册才合理，求您指导一下

**Comment by bunnyblue** [comment]
Activity.installContentProviders 没需求，之前搞过，加上了，遇到了点问题，有延时，就去掉了
