### ISSUE TITLE
插件怎么访问宿主的资源，如：string、color等

### ISSUE THREAD

**Issue by hpj831112** [bunnyblue/ACDD#44]
我看见你在宿主的工程下面有个public.xml的文件，插件的根目录下有个和它对应的文件，我尝试往里边加一些自己的资源，但是无法找到，请问还需要什么配置么？谢谢

**Comment by bunnyblue** [comment]
直接@就行了

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2016-01-29 17:11 GMT+08:00 hpj831112 <notifications@github.com>:
