### ISSUE TITLE
插件中的Activity只能继承Activity和FragmentActivity？

### ISSUE THREAD

**Issue by xbreezes** [bunnyblue/ACDD#46]
插件中的Activity只能继承Activity和FragmentActivity？继承AppcompatActivity 启动就会报AppTheme的错～

**Comment by bunnyblue** [comment]
插件中使用AppcompatActivity或者继承自AppcompatActivity是要设置主题，theme需要埋在宿主中，不能直接写在插件里面

**Comment by xbreezes** [comment]
```xml

 <public name="AppTheme" id="0x7f080077" type="style" />

 <activity
            android:name=".MainActivity"
            android:theme="@style/AppTheme">
```
还是提示You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by bunnyblue** [comment]
宿主里面注册activity了没？

**Comment by xbreezes** [comment]
注册了～
除了You need to use a Theme.AppCompat theme (or descendant) with this activity.
还有 ContextThemeWrapper_mResources is null paths in runtime:newDelegateResources

**Comment by bunnyblue** [comment]
你的AppcompatActivity是怎么弄进去的？导入的一个jar还是？

**Comment by xbreezes** [comment]
直接
```java
 compile 'com.android.support:appcompat-v7:22.2.1'
```

**Comment by bunnyblue** [comment]
不能这样写，appcompat这个编译到宿主中，不能直接编译到插件中，你可以这样调试，但是最终产生插件包的时候appcompat资源和代码应该都在宿主里面
