### ISSUE TITLE
关于aapt patch的问题

### ISSUE THREAD

**Issue by BaoBaoJianqiang** [bunnyblue/ACDD#47]
我比较了aapt目录下的源码，和系统自带aapt源码没有任何区别，请问具体修改了哪些代码？

**Comment by bunnyblue** [comment]
看patch吧

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2016-02-01 10:43 GMT+08:00 BaoBaoJianqiang <notifications@github.com>:

**Comment by BaoBaoJianqiang** [comment]
您好，我就是在ACDDExtension中查看appt和appt2目录，和源码没有区别，没找到您说的patch目录。请问在哪里？

**Comment by bunnyblue** [comment]
patch文件，不是目录

**Comment by BaoBaoJianqiang** [comment]
ACDD和ACDDExension中都没有patch文件，我看的是最新的版本。请问具体位置在哪里呢？文件全称？
