### ISSUE TITLE
插件资源问题

### ISSUE THREAD

**Issue by nervending** [bunnyblue/ACDD#48]
你好，在mi4 MIUI6.7.3.0（基于Android4.4.4）、moto （4.1.2） 上面插件的资源加载有问题，layout加载错误，
错误是Binary XML file line #9: Error inflating class

在华为手机emui3.1（5.1.1）上面程序运行就没有问题

请问有什么思路么？

**Comment by bunnyblue** [comment]
暂时没有这机器
demo跑起来报错吗

**Comment by nervending** [comment]
刚跑了一下，demo没有问题，
我们自己的项目有问题，正在比较看哪里有问题，我们项目是从一个旧有工程改过来的，代码量比较大，拆成了10个子模块。
你有什么想法么？大概会是哪里的问题？

**Comment by bunnyblue** [comment]
这个还真不太好说，是只有mi4 MIUI6.7.3.0（基于Android4.4.4）、moto （4.1.2）会有问题？别的机器都没有？
很奇怪，说不准哪儿的问题

**Comment by nervending** [comment]
手边的机器只试了这几个，
和demo做了两个很大的变化， 1 模块对主应用有代码依赖。 2 子模块Activity继承了 应用的的ActivityBase

对字模块 gradle 加了这个
gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        inputs.file "${rootDir}/rejoice/build/intermediates/classes-proguard/release/main.jar"
        inputs.file "${rootDir}/rejoice/build/generated/source/r/release/com/yuedong/sport/R.java"

        classpath = classpath.plus(files(
                "${rootDir}/rejoice/build/intermediates/classes-proguard/release/main.jar"
        ))
    }
}

帮忙看看 有没有问题

**Comment by nervending** [comment]
新年快乐，这个项目比较大，上线了 可以作为项目的一个实例应用

**Comment by bunnyblue** [comment]
模块对宿主有依赖,这样写应该没问题的，其实可以在依赖配置直接使用provided就行了，不用这么麻烦,插件里面不应该有宿主程序的代码资源。你这种写法不确定有没有问题吧
demo项目里面有个homelauncher，这样写的
```
dependencies {
    provided files('libs/android-support-v4.jar')
    provided files('libs/acdd.jar')
    provided files('libs/square-otto-1.3.2.jar')
    provided files('libs/export.jar')
}
```

**Comment by bunnyblue** [comment]
这个一般这样出现的，你看下Binary XML file line #9: Error inflating class出错的地方，aapt dump一下xmltree看下，如果自定义的布局的话看下，一般是内部出错了

**Comment by nervending** [comment]
对了 字模块的Activity 继承ActivityBase， ActivityBase使用的 宿主的资源 可能这里有错误，我试试。
我们项目比较大，搞定了上线 可以作为 一个线上应用实例

**Comment by hejie** [comment]
Error:Execution failed for task ':AppCenter:processAcddDebugAndroidTestResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/android-sdk-linux/build-tools/23.0.2/aapt'' finished with non-zero exit value 127

在linux环境 编译报错，什么原因呀？

**Comment by bunnyblue** [comment]
还有别的log吗，log太少，看不到

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by captainJeck** [comment]
修改一下插件ID，修改为0x13以上试试

**Comment by nervending** [comment]
最近重新整理了一下代码，
现在宿主的一个Actyivity都起不来了。。。
发现加载某两个模块就不行，不加载那两个就没问题
错误日志
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuedong.sport/com.yuedong.sport.ui.prepare.ActivityGuide}: java.lang.RuntimeException: (1)Paths in ContextThemeWrapper_mResources:[/system/framework/framework-res.apk, /system/app/miui.apk, /system/app/miuisystem.apk, /system/framework/framework-ext-res.apk, /data/app/com.yuedong.sport-1.apk, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_record_review.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_loc_map.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_push.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_stepdetector.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_sport.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_pay.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_feedback.so] paths in runtime:newDelegateResources [/data/app/com.yuedong.sport-1.apk,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_record_review.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_loc_map.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_push.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_stepdetector.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_sport.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_pay.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_feedback.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_zhpinyin.so,]
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:141)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:193)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.os.Looper.loop(Looper.java:136)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5072)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at dalvik.system.NativeStart.main(Native Method)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err: Caused by: java.lang.RuntimeException: (1)Paths in ContextThemeWrapper_mResources:[/system/framework/framework-res.apk, /system/app/miui.apk, /system/app/miuisystem.apk, /system/framework/framework-ext-res.apk, /data/app/com.yuedong.sport-1.apk, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_record_review.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_loc_map.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_push.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_stepdetector.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_sport.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_pay.so, /data/data/com.yuedong.sport/lib/libcom_yuedong_yue_feedback.so] paths in runtime:newDelegateResources [/data/app/com.yuedong.sport-1.apk,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_record_review.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_loc_map.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_push.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_stepdetector.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_sport.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_pay.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_feedback.so,/data/data/com.yuedong.sport/lib/libcom_yuedong_yue_zhpinyin.so,]
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at org.acdd.runtime.InstrumentationHook.HandleResourceNotFound(InstrumentationHook.java:307)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at org.acdd.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:547)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err: 	... 12 more
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err: Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class android.widget.Button
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:623)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at com.yuedong.sport.ui.base.ActivitySportBase.setContentView(ActivitySportBase.java:55)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at com.yuedong.sport.ui.prepare.ActivityGuide.onCreate(ActivityGuide.java:36)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.Activity.performCreate(Activity.java:5249)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at org.acdd.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:540)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err: 	... 13 more
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err: Caused by: java.lang.reflect.InvocationTargetException
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
02-25 14:49:15.693 10525-10525/com.yuedong.sport W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:597)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err: 	... 25 more
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/but_person_gradent.xml from drawable resource ID #0x7f020083
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2149)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:387)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2072)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.view.View.<init>(View.java:3562)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.widget.TextView.<init>(TextView.java:623)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.widget.Button.<init>(Button.java:107)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.widget.Button.<init>(Button.java:103)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err: 	... 28 more
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/but_white_press.xml from drawable resource ID #0x7f02009b
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2149)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:387)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2072)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:710)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:176)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:939)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.createFromXml(Resources.java:2525)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2145)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err: 	... 35 more
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err: Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:464)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:994)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:939)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.createFromXml(Resources.java:2525)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2145)
02-25 14:49:15.703 10525-10525/com.yuedong.sport W/System.err: 	... 43 more

**Comment by nervending** [comment]
发现加载了 那两个模块就会出问题 现在正在找为什么

**Comment by bunnyblue** [comment]
你看下 你的package id重复了没

**Comment by nervending** [comment]
发现是button background引起的问题，drawable 是xml的时候会出问题

**Comment by nervending** [comment]
我去解开模块包看看

**Comment by nervending** [comment]
是有我问题 资源id 没有按照要求的来

**Comment by nervending** [comment]
模块打包日志中 有这个 
--ACDD-resoure-id 35 --ACDD-shared-resources /Users/virl/wksp/yue/sports/rejoice/public.xml
Successfully started process 'command '/Users/virl/work/ide/android/sdk/build-tools/23.0.2/aapt''
Unknown source file : ***ACDD*** initACDDConig 35 
Unknown source file : ***ACDD*** initACDDConig /Users/virl/wksp/yue/sports/rejoice/public.xml 
Unknown source file : ***ACDD*** ACDD Shared Resource pkgGroup 35 
Unknown source file : PreDefine  Resource  Symbol  found 
可是生成的R文件里面 id 确实0x7F的。。。
这是我用错了么？

**Comment by nervending** [comment]
模块打包日志中 有这个 
--ACDD-resoure-id 35 --ACDD-shared-resources /Users/virl/wksp/yue/sports/rejoice/public.xml
Successfully started process 'command '/Users/virl/work/ide/android/sdk/build-tools/23.0.2/aapt''
Unknown source file : ***ACDD*** initACDDConig 35 
Unknown source file : ***ACDD*** initACDDConig /Users/virl/wksp/yue/sports/rejoice/public.xml 
Unknown source file : ***ACDD*** ACDD Shared Resource pkgGroup 35 
Unknown source file : PreDefine  Resource  Symbol  found 
可是生成的R文件里面 id 确实0x7F的。。。
这是我用错了么？

**Comment by bunnyblue** [comment]
aaptOptions.additionalParameters '--ACDD-resoure-id', '0x23', '--ACDD-shared-resources',rootProject.file("public.xml").getAbsolutePath() 这样写的？

**Comment by nervending** [comment]
def resourceId='0x7e'
    resourceId = mapPkgResId["${packageName}"]
    println "find packageName: " + "$packageName" + " ,resourceId:" + resourceId
    aaptOptions.additionalParameters '--ACDD-resoure-id', "$resourceId", '--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()

**Comment by bunnyblue** [comment]
resourceId是0x23？

**Comment by nervending** [comment]
对

**Comment by bunnyblue** [comment]
ACDDExtension  你试试这里面的，随便改个 id为0x23试试

**Comment by nervending** [comment]
是我那边给改错了

**Comment by nervending** [comment]
mapPkgResId = ['com.yuedong.yue.feedback'     : '0x20',
                       'com.yuedong.yue.im'           : '0x21',
                       'com.yuedong.yue.loc_map'      : '0x22',
                       'com.yuedong.yue.pay'          : '0x23',
                       'com.yuedong.yue.push'         : '0x24',
                       'com.yuedong.yue.record_review': '0x25',
                       'com.yuedong.yue.sport'        : '0x26',
                       'com.yuedong.yue.zhpinyin'     : '0x27',
                       'com.yuedong.stepdetector'     : '0x28']

productFlavors {
        acdd {
            def resourceId='0x7e'
            resourceId = mapPkgResId["${packageName}"]
            println "find packageName: " + "$packageName" + " ,resourceId:" + resourceId
            aaptOptions.additionalParameters '--ACDD-resoure-id', "$resourceId", '--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()
        }
    }

gradle 这样写 现在是打包资源id是对的，还在打包中

**Comment by bunnyblue** [comment]
@nervending 还不行？

**Comment by nervending** [comment]
暂时可以了，现在还有两个模块出问题。。。orz
一个是意见反馈 我们用的是友盟的sdk，反馈部分做了一个插件，现在是启动反馈页面
就会错误 日志：
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
at android.content.res.Resources.getValue(Resources.java:1133)
at android.content.res.MiuiResources.getValue(MiuiResources.java:145)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2363)
at android.content.res.Resources.getLayout(Resources.java:949)
at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)

我单独把这部分拎出去打包 作为独立apk运行 没问题，放在插件里面就不行了
友盟反馈sdk依赖于support-v4，不过我的support-v4是打包在宿主中的

**Comment by nervending** [comment]
还有一个就是使用环信sdk的im模块，
log和更早之前的有点类似
Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class <unknown>
at android.view.LayoutInflater.createView(LayoutInflater.java:623)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
at com.yuedong.sport.ui.base.ActivitySportBase.setContentView(ActivitySportBase.java:55)
at com.yuedong.sport.message.MsgHomeActivity.onCreate(MsgHomeActivity.java:69)
at android.app.Activity.performCreate(Activity.java:5249)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at org.acdd.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:540)
... 13 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at android.view.LayoutInflater.createView(LayoutInflater.java:597)
... 26 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=13; index=13
at android.content.res.AssetManager.getPooledString(AssetManager.java:282)
at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:727)
at android.content.res.TypedArray.getValueAt(TypedArray.java:712)
at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
at android.widget.TextView.<init>(TextView.java:960)
at android.widget.Button.<init>(Button.java:107)
at android.widget.CompoundButton.<init>(CompoundButton.java:68)
at android.widget.RadioButton.<init>(RadioButton.java:63)
at android.widget.RadioButton.<init>(RadioButton.java:59)
看资源id是对的，现在正在找看看什么原因

**Comment by bunnyblue** [comment]
uemng的意见反馈那边取资源这样，不知道是不是这个原因，我有空也研究下
```Java
  public static synchronized Res getInstance(Context paramContext)
  {
    if (b == null)
    {
      c = c != null ? c : paramContext.getPackageName();
      b = new Res(c);
    }
    return b;
  }
  ```

**Comment by nervending** [comment]
好的 多谢 我去继续找im那边的问题

**Comment by nervending** [comment]
debug跟进资源id是对的，我代码获取是那个资源是没问题，写在xml里面就不行
ColorStateList colorStateList = getResources().getColorStateList(R.color.easembo_tab_text_selector);
是因为是ColorStateList的原因么？单独使用其他的color都没问题

**Comment by bunnyblue** [comment]
友盟的问题这样子，可能需要对友盟的sdk修改，他的包名解析有问题
```Java
02-26 18:44:52.970 25979-25979/org.acdd.launcher E/com.umeng.fb.util.Res: org.acdd.launcher.R$array
02-26 18:44:52.970 25979-25979/org.acdd.launcher E/com.umeng.fb.util.Res: getRes(org.acdd.launcher.R$layout, umeng_fb_activity_help)
02-26 18:44:52.970 25979-25979/org.acdd.launcher E/com.umeng.fb.util.Res: Error getting resource. Make sure you have copied all resources (res/) from SDK to your project. 
02-26 18:44:52.970 25979-25979/org.acdd.launcher E/com.umeng.fb.util.Res: umeng_fb_activity_help
```

**Comment by nervending** [comment]
好的 多谢，友盟的我再想办法吧
另一个模块我再明确一下问题

**Comment by nervending** [comment]
![image](https://cloud.githubusercontent.com/assets/5318103/13353128/1c216710-dccd-11e5-844c-4fe1f7427c4e.png)
发现很奇怪的现象，我debug，这些资源都可以，放在layout 的xml文件里就不行

**Comment by bunnyblue** [comment]
@nervending  umeng的问题这样解决的，你可以参考下https://github.com/bunnyblue/ACDDExtension/blob/master/Samples/Feedback/src/main/java/com/umeng/fb/example/MainActivity.java Res是个单例模式，创建一个假的context，修改下包名就行了，另一个问题你看看有折中的解决方案没，没带电源，CPU降频了，卡

**Comment by nervending** [comment]
多谢了，我试一下

**Comment by nervending** [comment]
发现还是不行，umeng 那边是这么用反射的
Class.forName(var1 + ".R$drawable");
默认的classLoader 是找不到这个类的。。。。
还有他的getInstance方法 在Activity onCreate中就会被调用，所以假的context不会生效
我现在是这么干的。。
static {
        Res.setPackageName("com.yue.yue.feedback");
    }
剩下就是发现他的反射找不到类

**Comment by nervending** [comment]
现在可以了 不过不是用你给的方法，因为我debug发现他在早于Activity onCreate之前Res就会初始化
是直接设置一下
static {
        Res.setPackageName("com.yuedong.yue.feedback");
    }
非常感谢你

**Comment by nervending** [comment]
找到错误原因了 是我使用错误了
DelegateResources的方法里面有线程要求 我有几个模块是异步加载的 所以Assert Path没有加载进去
    public static void newDelegateResources(Application application, Resources resources, String newPath) throws Exception {
        if (Thread.currentThread().getId() == Looper.getMainLooper().getThread().getId()) {
            newDelegateResourcesInternal(application, resources, newPath);
            return;
        }
        synchronized (lock) {
            new Handler(Looper.getMainLooper()).post(new DelegateResourcesGetter(application, resources, newPath));
            lock.wait();
        }
    }

**Comment by bunnyblue** [comment]
有几个启动模式，你可以把延时启动的放delay里面或者store里面

**Comment by nervending** [comment]
好的 多谢

**Comment by nervending** [comment]
非常感谢 有时间一起吃饭 也可以来我们公司参观，我们在深圳

**Comment by bunnyblue** [comment]
😄
