### ISSUE TITLE
build.tool.R23 / linux-x86 在linux环境下如何替换？ 报错如下

### ISSUE THREAD

**Issue by hejie** [bunnyblue/ACDD#49]
Error:Execution failed for task ':AppCenter:processAcddDebugAndroidTestResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/android-sdk-linux/build-tools/23.0.2/aapt'' finished with non-zero exit value 127

**Comment by bunnyblue** [comment]
解决了没？

**Comment by hejie** [comment]
没呢，求解决 ，不清楚linux环境下 你的 linux-x86 目录下有几个文件，都要替换？

**Comment by hejie** [comment]
现在好了，谢谢呀，还是自己弄错文件了
