### ISSUE TITLE
关于通信

### ISSUE THREAD

**Issue by dashen19930328** [bunnyblue/ACDD#5]
您好，我想问的是，宿主程序与服务器交互通信，插件模块在宿主中运行，其与服务器的交互，应该是需要通过宿主来中转的吧，如何是，是不是需要建立一个消息中心，那感觉很复杂啊，针对不同的消息类型会有不同的处理动作，请您指导一下，不甚感激！

**Comment by bunnyblue** [comment]
单进程模式，插件个宿舍在一个进程
