### ISSUE TITLE
module signature in root device

### ISSUE THREAD

**Issue by nervending** [bunnyblue/ACDD#53]
我们做了一个接口，给第三方开放 允许他们做插件 接入我们，
现在遇到的问题 就是签名问题，
SecurityBundleListner.PUBLIC_KEY 已经修改为我们的key了
然后第三方做的插件我是这样给签名的
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keysotre.keystore -storepass storepass -keypass keypass -signedjar sign2.apk unsign.apk public

可是在root手机上面会效验public_key,发现效验不过。。
请问 是我签名的方法错了 还是怎样的？
我们自己打包的模块没问题，别人打包的没签名 我做了签名就不可以

非常感谢，我们的产品已经在测试了，第一版马上就发布，第二版就会发布 模块更新和第三方插件接入。

**Comment by bunnyblue** [comment]
检测下apk签名是否一致，你这样签名的apk可以直接安装到系统吗，你的JDK是6以上版本的话需要----sigalg MD5withRSA 参数http://www.informit.com/articles/article.aspx?p=1966023&seqNum=2

**Comment by nervending** [comment]
刚用 下面命令 签名了，可以独立安装，加载之后同样的不通过
jarsigner -verbose -keystore ../rejoice/rejoice.keystore unsign.apk -digestalg SHA1 -sigalg MD5withRSA release
我的java 版本
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Comment by bunnyblue** [comment]
你看下公钥没读出来还是不一样？

**Comment by nervending** [comment]
不一样，等我再debug 确认下

**Comment by nervending** [comment]
jarEntry.getCodeSigners() 获取到的都不一样
里面Subject 以及Key: OpenSSLRSAPublicKey 和 有效期都不一样，
最终生成的公钥也不一样，我再去找找 原因

**Comment by bunnyblue** [comment]
确定之前的unsigned是未签名的？keystore的cert不会变

**Comment by nervending** [comment]
确认问题了，签名没错，是之前测试在sd卡放了一个 签名有问题的包，优先加载了sd卡上面的包了。。
orz。。。。。做了一件蠢事

**Comment by nervending** [comment]
debug发现签名信息不对，刚又写了一个程序把apk的签名信息输出到文件，结果发现是正确的，然后最终发现 加载的插件错误
