### ISSUE TITLE
模块升级问题

### ISSUE THREAD

**Issue by nervending** [bunnyblue/ACDD#54]
发现 BundleInfo里面version并没有被使用，当模块修改代码并升级versionCode和versionName之后，ACDD并没有装载最新的so，是不是这个操作要 自己来管理？

**Comment by nervending** [comment]
看代码 感觉是这样子的，不知道有没有理解错误

**Comment by bunnyblue** [comment]
是这样子，如果宿主版本号不变的话需要手动更新。这部分没写还

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by nervending** [comment]
好的 多谢
