### ISSUE TITLE
请问如何进行插件升级

### ISSUE THREAD

**Issue by youtian** [bunnyblue/ACDD#57]
HI，看到wiki上写的支持插件升级，但没找到相关说明，请问一下怎么升级呢？

**Comment by bunnyblue** [comment]
updateBundle Javadoc文档里面有


 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by youtian** [comment]
好的，非常感谢！

**Comment by bunnyblue** [comment]
ext home launcher里面有个update qrcode 你可以参考那个
