### ISSUE TITLE
关于插件之间的包等资源共享问题

### ISSUE THREAD

**Issue by dashen19930328** [bunnyblue/ACDD#6]
osgi中bundle可以通过import export实现包共享，但是这个框架插件编译生成好后是apk文件格式，只有在osgi启动加载后bundle化，但这时候怎么做到包共享呢？请您百忙之中抽空指导一下

**Comment by bunnyblue** [comment]
插件 AndroidManifest meta 注册依赖 'dependency' 如果有多个的话逗号分隔，你说的共享是这个意思？

**Comment by dashen19930328** [comment]
就是比如写了一个通用类，希望只在一个bundle中出现一次，我其他bundle不用重写引用就好，我说的是这个意思

**Comment by bunnyblue** [comment]
插件 AndroidManifest meta 注册依赖 'dependency' 如果有多个的话逗号分隔
