### ISSUE TITLE
Hi，用ACDD遇到一个问题关于旧插件覆盖新插件的问题

### ISSUE THREAD

**Issue by aliencool** [bunnyblue/ACDD#60]
我有旧插件有个数据库文件，新插件有个对这个数据库文件进行修改的新文件，此时覆盖安装（旧被覆盖掉），新数据库文件只有杀进程后才生效，请问如何不杀进程后生效呢？谢谢

**Comment by bunnyblue** [comment]
默认升级后再启动才生效，你用的那种升级方式，强制升级吗

**Comment by aliencool** [comment]
再启动是指什么意思呢？强制重启（杀死干净）吗？
我使用的升级是：updateBundle，谢谢

**Comment by bunnyblue** [comment]
https://github.com/bunnyblue/ACDD/commit/96912f2390ce024f6482632a77aea276650f8702

如果你的插件没有依赖的话可以使用updateBundleForce进行更新

**Comment by aliencool** [comment]
请问如何理解没有依赖？没有依赖宿主的东西吗？谢谢

**Comment by bunnyblue** [comment]
其余的插件没有依赖你这个插件的话，可以强制更新，如果你的插件被其余的组件依赖的话不行

**Comment by aliencool** [comment]
还想请叫下updateBundle 和 updateBundleForce有什么本质的区别？看了注释说这个不稳定，谢谢

**Comment by bunnyblue** [comment]
updateBundle一般是下次启动生效，updateBundleForce这个的话强制更新，把运行的组件停止再更新，这个没经过大范围的测试

**Comment by aliencool** [comment]
谢谢啦

**Comment by aliencool** [comment]
Hi，我刚才是用了updateBundleForce  
  public void updateBundleForce(String pkgName, File mBundleFile)
            throws BundleException {
        if (!mBundleFile.exists()) {
            throw new BundleException("file not  found" + mBundleFile.getAbsolutePath());
        }
        BundleImpl bundle = (BundleImpl) Framework.getBundle(pkgName);
        if (bundle != null) {
            bundle.update(mBundleFile);
            bundle.refresh();
            try {
                DelegateResources.newDelegateResources(RuntimeVariables.androidApplication, RuntimeVariables.delegateResources, bundle.getArchive().getArchiveFile().getAbsolutePath());
            } catch (Exception e) {
            }
            return;
        }
        throw new BundleException("Could not update bundle " + pkgName
                + ", because could not find it");
    }后并没有什么效果
