### ISSUE TITLE
aapt源码编译；Service问题

### ISSUE THREAD

**Issue by huzgHost** [bunnyblue/ACDD#61]
@bunnyblue 
想问一下，帮忙解答一下，谢谢
1,下了android6.0的源码，直接替换aapt目录代码，编译生成的aapt 9M左右，为什么这里才1.3M？
   有替换过androidfw，生成生成so, 貌似这个so没啥用，aapt只需要它的头文件

2，关于Service,貌似只能StartService,但这满足不了想实现的东西， 想通过bindService来得到Service的控制权，失败。通过Proxy也是不行的。 最后只能通过Receiver不同的action来调用插件的功能。

**Comment by bunnyblue** [comment]
Service支持 bind启动。
9M因为到了符号，把符号去掉了就小了
aapt使用的是静态库引用，如下，具体看mk
```
aaptHostStaticLibs := \
    libandroidfw \
    libpng \
    liblog \
    libutils \
    libcutils \
    libexpat \
    libziparchive-host \
    libbase
```

**Comment by huzgHost** [comment]
1，关于Service, 我是想在Host中去bind 插件的Service.. 这样就可以控制插件的Service去调用相应的功能。  本来想通过Binder，获取到Service,就是跨进程调用啦。结果发现并不可行。

2，去掉符号？没听明白，mk文件都是除了新增的类，其它都一样。

**Comment by bunnyblue** [comment]
2 去掉符号这个strip去掉
1 以前都是组件内部bind，Host中去bind 插件的Service，应该是可以，但是这个没具体测试

**Comment by huzgHost** [comment]
1，之前用的setAction来启动, 一直不成功；setClassName可行。 已经测试了。

2，静态库只需要link，你的意思是已经打包进去了？
你的意思，
#ifneq ($(strip $(USE_MINGW)),)
ifneq ($(USE_MINGW),)   #更改成这样？
    aaptHostStaticLibs += libz
else
    aaptHostLdLibs += -lz
endif

貌似没啥改变 …………

看到注释，说是linux sdk 用到的MinGW 的一些库？  这什么意思

**Comment by bunnyblue** [comment]
man strip， Google一下就有答案

**Comment by bunnyblue** [comment]
MinGW 这是是编译windows版本的aapt用的，Windows版本也是需要在Linux下编译，使用MinGW

**Comment by huzgHost** [comment]
strip  去掉USE_MINGW中的空格。 然后判断不为空为true，    我记得在编译的时候需要安装mingw32。
生成bin文件，我试过不用libapp包，直接自己引入 
LOCAL_SRC_FILES := $(aaptMain) $(aaptSources)
LOCAL_C_INCLUDES += $(aaptCIncludes)

 有一大把错误，郁闷了～～～

**Comment by bunnyblue** [comment]
不要修改这个，编译完了strip二进制文件，不是man strip， Google一下就有答案

**Comment by huzgHost** [comment]
原来是脱衣，知道了。  我一直以为是编译出的问题   囧囧囧
谢谢 @bunnyblue

**Comment by huzgHost** [comment]
怎么搞定不同平台的aapt呢？
win, linux, mac

目前编译原来得到的有7M多，脱衣后只有1.1M
tab@tab-PC:/workspace/Works/AndroidSource/6.0/mydroid/out/host/linux-x86/bin$ ls -ahl aapt 
-rwxrwxr-x 1 tab tab 1.1M  4月 26 13:54 aapt

**Comment by bunnyblue** [comment]
Linux在Linux上面编译，没问题吗？
Windows平台的 make aapt USE_MINGW=y
应该是这样，我记得在extention里面写了

Mac的需要在mac下面编译，源码很大，啊哈哈，当初我这样做的，LinuxSamba开启文件共享，你需要一个虚拟机或者mac，通过文件共享打开，然后编译就行了，我在Ubuntu安装了个虚拟机，这样快一点

**Comment by huzgHost** [comment]
在linux编译下没问题啊，我直接mmm编译的，没看到任何问题。
mmm 好像不能传参数。 
win的
tab@tab-PC:/workspace/Works/AndroidSource/6.0/mydroid$ ls -hal out/host/windows-x86/bin/aapt.exe 
-rwxrwxr-x 1 tab tab 16M  4月 26 15:01 out/host/windows-x86/bin/aapt.exe
脱衣后：
tab@tab-PC:/workspace/Works/AndroidSource/6.0/mydroid$ strip out/host/windows-x86/bin/aapt.exe
tab@tab-PC:/workspace/Works/AndroidSource/6.0/mydroid$ ls -hal out/host/windows-x86/bin/aapt.exe 
-rwxrwxr-x 1 tab tab 1.5M  4月 26 15:03 out/host/windows-x86/bin/aapt.exe

从16M 直接到1.5M 

mac就算了，没环境

**Comment by bunnyblue** [comment]
mac可以安装个虚拟机，然后就可以了，然后安装个xcode，挂在Linux的源码编译就行了
