### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kenvies** [bunnyblue/ACDD#62]
* What went wrong:
Execution failed for task ':HomeLauncher:processAcddDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android_config\sdk2\sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 2
替换aapt之后还是会报这个错误，是什么原因呢

**Comment by bunnyblue** [comment]
gradle assembleDebug --info 看下 这个错误是aapt异常退出了，在资源有问题的情况下aapt会杀掉进程

**Comment by kenvies** [comment]
那我该怎么查看有问题的资源，或者说怎么去解决这个问题呢？

**Comment by bunnyblue** [comment]
打开log看下 或者直接运行gradle assembleDebug --info ，studio的话找到gradle 加上 --info

**Comment by kenvies** [comment]
C:\Users\zhang>gradle assembleDebug --info
Starting Build
Settings evaluated using settings file 'C:\master\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\zhang\build.gradle'.
Included projects: [root project 'zhang']
Evaluating root project 'zhang' using build file 'C:\Users\zhang\build.gradle'.
All projects evaluated.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleDebug' not found in root project 'zhang'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --debug                                                                                                                        option to get more log output.

BUILD FAILED

Total time: 1.857 secs

**Comment by bunnyblue** [comment]
C:\master\settings.gradle? C:\Users\zhang\build.gradle你的目录好奇怪啊

**Comment by canney-chen** [comment]
me.开头的包名插件不能生成bundle-info

**Comment by dashen19930328** [comment]
hello,have you solved the problem?i meet the same problem.

**Comment by tcking** [comment]
gradle android plugin 版本需要低于2.1

**Comment by dashen19930328** [comment]
why we need the version below 2.1,i have another problem,the demo i write whose id is ox7f which seems not in ox20 to ox7e

**Comment by bunnyblue** [comment]
@canney-chen  目前只有 com和 cn 别的没支持
@dashen19930328   资源id需要自己配置，不然就是0x7f
