### ISSUE TITLE
热更新

### ISSUE THREAD

**Issue by 4210048** [bunnyblue/ACDD#67]
您好，插件支持热更新吗？不需要重启宿主

**Comment by bunnyblue** [comment]
可以，如果插件没有依赖的话（不被其余的依赖），ACCD 里面有强制更新

**Comment by 4210048** [comment]
测试独立插件，使用如下方法
ACDD.getInstance().updateBundleForce("com.acdd.qrcode",file);
不起作用，更新后，依然要重启宿主app,如何解决？

**Comment by bunnyblue** [comment]
这个插件被其余的插件依赖吗

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=8.6.51&pv=10.12.0&source=email_footer_2]
On Wed, Sep 14, 2016 at 6:37 PM, 4210048 <notifications@github.com> wrote:
测试独立插件，使用如下方法
ACDD.getInstance().updateBundleForce("com.acdd.qrcode",file);
不起作用，更新后，依然要重启宿主app,如何解决？

**Comment by 4210048** [comment]
没有依赖，直接使用github上的ACDD和AcddExtension测试的，略作修改，放了两个button,一个更新，一个用来启动，用的Samples中的QRCode,把这个插件略微修改了，放在/sdcard/路径下，更新这个插件，测试更新后不重启，是不是生效，结果未生效。

![image](https://cloud.githubusercontent.com/assets/18549574/18543944/e217cb36-7b64-11e6-89c8-cb585269a9c3.png)
