### ISSUE TITLE
宿主工程

### ISSUE THREAD

**Issue by dashen19930328** [bunnyblue/ACDD#68]
你好，我想问问，能不能把自己现有的工程在ACDD的基础上进行修改，成为宿主工程，感觉好像很复杂，会有很多问题，求解答

**Comment by bunnyblue** [comment]
可以啊，看get star ，wiki里面，这部分就是一个jar 还有so，so可选的是

**Comment by dashen19930328** [comment]
你好，我现在已经将我们的工程整合到框架中，现在有如下几个问题：1.根据那个ACDDExtension好像现在插件对应的信息就是根据packagename,那几个.so插件demo是根据lib插件名获取package名从而获取详细信息生成json，可是现在我想动态安装插件能不能动态匹配图片与文字显示在宿主工程的导航页上；2.做安装时发现好像需要自己修改，并不能直接调用ACDD中的方法，不然每次重启都会不见，可是存储目录下还是有的，但是因为加载安装方式不是auto所以不能加载出来；3.我想问这个框架最后能不能实现动态动态加载，如果插件开发需要在mainfest.xml中声明组件，又怎么加动态加载，望您解答

**Comment by bunnyblue** [comment]
1. 这个是可以的，不过你需要把你的插件的资源手动更新到list里面，这部分没有直接暴露，你添加去就可以了（最近生病，一直没改） 2.这个刚开始是全部加载的，后来考虑到内存什么的，重启后只加载的auto，其余的虽然有，但是默认没加载（这部分 private static int restoreProfile() {这里面判断了只还原auto类型的 ），你可以跟以前那样调用一次安装，或者修改下这儿 3. ACDDConfig.stubModeEnable= true ; 这个开启可以免注册activity 和receiver，不过这个当初是实验性功能，要是用的话还是仔细测下，测试没问题，但是机器不多

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.12.46&pv=10.12.0&source=email_footer_2]
On Tue, Jul 19, 2016 at 6:48 PM, Mr.baicai <notifications@github.com> wrote:
你好，我现在已经将我们的工程整合到框架中，现在有如下几个问题：1.根据那个ACDDExtension好像现在插件对应的信息就是根据packagename,那几个.so插件demo是根据lib插件名获取package名从而获取详细信息生成json，可是现在我想动态安装插件能不能动态匹配图片与文字显示在宿主工程的导航页上；2.做安装时发现好像需要自己修改，并不能直接调用ACDD中的方法，不然每次重启都会不见，可是存储目录下还是有的，但是因为加载安装方式不是auto所以不能加载出来；3.我想问这个框架最后能不能实现动态动态加载，如果插件开发需要在mainfest.xml中声明组件，又怎么加动态加载，望您解答
