### ISSUE TITLE
想请教一下ACDD SDK 使用情况

### ISSUE THREAD

**Issue by makuku** [bunnyblue/ACDD#69]
bunnyblue：你好，  因为我研究了一下SAMLL发现不是很稳定，比较多的异常情况没有考虑到。所以，我想知道  ACDD有没有使用到具体哪个产品中去吗？稳定性怎么样？尤其是资源ID处理。期待你的回复。

**Comment by bunnyblue** [comment]
应该好几个，根据反馈还不错（具体哪些吧，人家也没在这上面提，所以） 资源的修改了aapt，修改了0x7f，目前对Android N在动态库加载这块异常（git 上有这个issue），前一阵子生病，一直没开电脑。稳定性还不错。

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.12.46&pv=10.12.0&source=email_footer_2]
On Tue, Jul 19, 2016 at 2:59 PM, makuku <notifications@github.com> wrote:
bunnyblue：你好， 因为我研究了一下SAMLL发现不是很稳定，比较多的异常情况没有考虑到。所以，我想知道 ACDD有没有使用到具体哪个产品中去吗？稳定性怎么样？尤其是资源ID处理。期待你的回复。

**Comment by makuku** [comment]
你们 自己的产品有使用吗？

**Comment by bunnyblue** [comment]
也算是用了
via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.12.46&pv=10.12.0&source=email_footer_2]
On Tue, Jul 19, 2016 at 3:42 PM, makuku <notifications@github.com> wrote:
你们 自己的产品有使用吗？
