### ISSUE TITLE
关于build的错误

### ISSUE THREAD

**Issue by Apollolight** [bunnyblue/ACDD#7]
task acddWrapBundle << {

    javaexec {
        classpath "$projectDir/ACDDExt.jar"
        main = 'org.acdd.ext.bundleInfo.maker.BundleMakeBooter'
        args "$projectDir/libs/armeabi".toString(), "$projectDir/assets/bundle-info.json".toString(),"$projectDir/.bundleCache"
    }
}
assembleDebug.dependsOn(acddWrapBundle)
assembleRelease.dependsOn(acddWrapBundle)

在android studio 中build时，需要把上面这段代码删除才能BUILD，这是为啥，希望能解读一下，谢谢

**Comment by bunnyblue** [comment]
可能这段代码有bug，来了用于自动生成组件信息的。文档可以看下wiki

 Across the Great Firewall, you can reach every corner in the world.
                                                          *Best Regards*

**Comment by Apollolight** [comment]
万分感谢

**Comment by Apollolight** [comment]
万分感谢
