### ISSUE TITLE
无法编译运行，以及运行后只能启动ACTIVITY的问题

### ISSUE THREAD

**Issue by Apollolight** [bunnyblue/ACDD#8]
task acddWrapBundle << {

    javaexec {
        classpath "$projectDir/ACDDExt.jar"
        main = 'org.acdd.ext.bundleInfo.maker.BundleMakeBooter'
        args "$projectDir/libs/armeabi".toString(), "$projectDir/assets/bundle-info.json".toString(),"$projectDir/.bundleCache"
    }
}
assembleDebug.dependsOn(acddWrapBundle)
assembleRelease.dependsOn(acddWrapBundle)

1.具体问题：   上面这段代码中的ACDDExt.jar包无法找到，导致无法运行。
2.分析可能原因： 对比之前的OPENATLAS项目发现，目前的项目少了一个bundler的module,是否是因为将该MODULE集成到了ACDDExt.jar包中。
3.将此段代码删除，可以运行项目，但是只能打开里面的ACTIVITY，而不能运行SERVICE等其他组件，不知是否是因为这段代码的缘故。

**Comment by bunnyblue** [comment]
ACDDExt.jar位于 ACDDExt，如果你自己的，你看下啥问题，debug下，最近忙，等有空在研究，不能运行的话提供log出来，不然没法定位
