### ISSUE TITLE
Stub Mode Support

### ISSUE THREAD

**Issue by bunnyblue** [bunnyblue/ACDD#9]
Add  stub mode  support

**Comment by bunnyblue** [comment]
testing

**Comment by hejie** [comment]
support stub mode 是什么意思？，不太理解

**Comment by bunnyblue** [comment]
免注册启动

**Comment by hejie** [comment]
看代码好像是模拟了 PackageManagerService 的实现，不清楚这个免注册启动是在哪里为入口的，是 *ContextImplHook
？😇*

2016-03-17 10:14 GMT+08:00 Bunny Blue <notifications@github.com>:

>  免注册启动
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bunnyblue/ACDD/issues/9#issuecomment-197655571>
>



-- 
内容：

*顺  祝  工  作  顺  利!*


*研发部     何杰*

*电话：**18667168171          **邮编：**200081*

**Comment by hejie** [comment]
就是不太熟悉这个免注册的原理，您有空帮我稍微讲解下哈，太感谢了！！

在 2016年3月18日 下午12:58，何杰 <hj7.com@gmail.com>写道：

>  看代码好像是模拟了 PackageManagerService 的实现，不清楚这个免注册启动是在哪里为入口的，是 *ContextImplHook
> ？😇*
>
> 2016-03-17 10:14 GMT+08:00 Bunny Blue <notifications@github.com>:
>
>>  免注册启动
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bunnyblue/ACDD/issues/9#issuecomment-197655571>
>>
>
>
>
> --
> 内容：
>
> *顺  祝  工  作  顺  利!*
>
>
> *研发部     何杰*
>
> *电话：**18667168171 <18667168171>          **邮编：**200081*
>
>
>


-- 
内容：

*顺  祝  工  作  顺  利!*


*研发部     何杰*

*电话：**18667168171          **邮编：**200081*

**Comment by bunnyblue** [comment]
在清单注册了一个不存在的Activity 告诉AMS启动，AMS启动记录信息。然后ActivityThread把空壳的Activity替换掉，AMS启动的Shell，运行的时候Shell已经被替换成目标。
开启Stub后。Activity可以不用注册，看log启动的是org.acdd.runtime.stub.StubActivity，当初考虑到了一下，还是默认关闭了，这部分不复杂,启动Activity的时候跑检测Activity是否注册，没注册的话把Intent更改为StubActivity，接下来的事情AMS处理，从AMS回来的时候检测一下是不是StubActivity，如果是的话把数据恢复回来在，把类名替换回去

```
    public static void processActivityIntentIfNeed(Object obj) {

        try {
            Class cls = Class.forName("android.app.ActivityThread$ActivityClientRecord");
            Field declaredField = cls.getDeclaredField("intent");
            declaredField.setAccessible(true);
            Intent intent = (Intent) declaredField.get(obj);
            Bundle bundle = sTargetBundleStorage.poll();
            if (intent.getComponent() != null && intent.getComponent().getClassName().equals(InternalConstant.STUB_STUB_ACTIVITY)) {
                Field activityInfo = cls.getDeclaredField("activityInfo");
                activityInfo.setAccessible(true);
                String string = bundle.getString(InternalConstant.STUB_DATA);
                if (!TextUtils.isEmpty(string)) {
                    if (string == null) {
                        string = null;
                    }
                    intent.setData(Uri.parse(string));
                }
                intent.setClassName(RuntimeVariables.androidApplication.getPackageName(), bundle.getString(InternalConstant.STUB_TARGET));
                //if(!TextUtils.isEmpty(bundle.getString(InternalConstant.STUB_TARGET)))
                Object rec  = ((BundleImpl) ACDD.getInstance().getBundle(
                        bundle.getString(InternalConstant.STUB_BUNDLE_LOCATION))).
                        getPackageManager().
                        activityIntentResolver.componentHashMap.get(intent.getComponent());
                intent.removeExtra(InternalConstant.STUB_BUNDLE_LOCATION);
                if (rec == null) {
                    return;
                }
                Object value = Class.forName("android.content.pm.PackageParser$Activity").getField("info").
                        get(rec);
                activityInfo.set(obj, value);
                log.debug("run on portable  mode");
            }
        } catch (ClassNotFoundException th) {
            th.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }
    }
```
