### ISSUE TITLE
经测试，没有使用v7包的时候可以不在宿主注册activity，有使用的话一定的注册才可以。

### ISSUE THREAD

**Issue by leafseelight** [bunnyblue/ACDD#9]
想问下是为什么？补充下，是指Activity继承AppCompactActivity

**Comment by bunnyblue** [comment]
你需要设定theme，预先占的坑没有设定theme

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by leafseelight** [comment]
*thanks*
对的，theme不是AppCompact的也不可以，需要theme预先占坑AppCompact下的theme，加上宿主清单文件配置Activity。不是继承AppCompactActivity的就不用在宿主上注册。

**Comment by bunnyblue** [comment]
theme 这个问题，如果你要用的话，只能代码里面设置了
